### PR TITLE
Remove nextTick() and NextTickQueue

### PR DESCRIPTION
**Pull request by clue**
~~This PR is a RFC – any input is welcome.~~

v0.4 introduced both "future ticks" and "next ticks".

~~This PR aims to serve as a discussion basis whether it actually makes sense to keep both.~~

Edit: This PR removes the `nextTick()` method and its underlying `NextTickQueue` implementation. Use the `futureTick()` method instead.

### CODE REVIEW

**Comment by clue** [comment]
For the reference, both queues have been implemented by @jmalloc via https://github.com/reactphp/react/pull/234 and https://github.com/reactphp/react/pull/249 respectively. Let's ping @jmalloc, perhaps you can share your view on this?

There's also some discussion / confusion about this topic in https://github.com/reactphp/event-loop/pull/28:
> here's probably some discussion to be had about how necessary this is. I think it is necessary, as without it there is no way to execute user code on each tick of the engine without starving IO/timers (nextTick is too greedy).
> The implementation is identical to nextTick, except that callbacks registered inside an existing futureTick handler will not be processed on the same tick. In other words, when the future-tick queue is processed, only the callbacks that were already on the queue are executed. With this implementation, futureTick should generally be favoured over nextTick unless you specifically need the stricter guarantees of nextTick.

Long story short, cooperative multitasking will likely depend on `futureTick()` instead of `nextTick()`.

I'm still curious if we have a valid use case for `nextTick()`, i.e. explicitly starving the event loop if we repeatedly add events to the loop. Otherwise, I'd suggest removing the `nextTick()` method as per this PR.

For what it's worth, nodejs also has:
* https://nodejs.org/api/timers.html#timers_setimmediate_callback_arg (similar to futureTick())
* https://nodejs.org/api/process.html#process_process_nexttick_callback_arg (similar to nextTick())

**Comment by clue** [comment]
> For what it's worth, nodejs also has:
*    https://nodejs.org/api/timers.html#timers_setimmediate_callback_arg (similar to futureTick())
*    https://nodejs.org/api/process.html#process_process_nexttick_callback_arg (similar to nextTick())

Afaict there's also debate about which function should be used, e.g. see http://stackoverflow.com/a/15349865

I'm well aware of the differences between both functions. However, I have yet to find a valid use case for `nextTick()`…

**Comment by WyriHaximus** [comment]
:+1: on removing next ticks, it just adds confusion without a real good use case for keeping them

**Comment by jmalloc** [comment]
I can't see any immediate reason to retain `nextTick`. For whatever it's worth, the only large project I have using React is [Recoil](https://github.com/recoilphp/recoil) and it does not use `nextTick` at all.

**Comment by jmalloc** [comment]
I'd also like to add that I was never quite happy with the name `futureTick`. Since this is a BC break anyway, maybe we could consider more appropriate names.  `$loop->defer($work);` might make more sense?

**Comment by WyriHaximus** [comment]
I'm with @jmalloc renaming `futureTick` to `defer` is a great idea :+1:

**Comment by cboden** [comment]
I'm ok with renaming and `defer` makes sense grammatically, however I do worry about the confusion of the word. React also houses the `Promise` library where invoking a defer call created a deferred object that can resolve or reject a promise object.

**Comment by jmalloc** [comment]
That's a valid concern for sure. I still personally prefer `defer`, but offer `enqueue` as a possible alternative. At any rate, I think it should be a verb :)

**Comment by nrk** [comment]
I'm with @cboden regarding the potential confusion of using `defer` but well that's actually what it does... maybe `postpone`? I do agree on the fact that the current `futureTick` and `nextTick` are awful names, after all we had the same discussion at the time of @jmalloc's PR from a while back and we couldn't come up with valid alternatives.

Back to the initial scope of this PR, I'm still torn about removing `nextTick` altogether but I don't have a strong and practical use case to support it.

**Comment by cboden** [comment]
Ye old thesaurus came up with a few options, my top ones:

* delay
* postpone
* mothball

I agree that defer is grammatically correct but, to me, it's synonymous with containing a promise object - which is not the case in this context.

**Comment by WyriHaximus** [comment]
For me both enqueue or schedule would work

**Comment by yriveiro** [comment]
The term `schedule` seems good enough to understand that you're deferring the task to other loop iteration. With `enqueue`, you don't know if you are enqueuing for this loop iteration or not, It is not as explicit as `schedule`.

As a non experienced user of reactphp (I started to read the code last week), my first thought after read `defer` was: this return a promise?

**Comment by jsor** [comment]
👍 for removing `nextTick`. Also 👍 for renaming `futureTick` to `defer`.

**Comment by nrk** [comment]
I just noticed that I used `nextTick` only one time in predis\async to fix an issue but it's old stuff (and so damn _un-Reacty_ anyway at this point) and I guess `futureTick` would've probably worked anyway. All in all I wouldn't mind having `nextTick` removed. As for `futureTick`, despite being an awful name I still have doubts about renaming it to `defer`.

**Comment by jsor** [comment]
Btw, the async-interop loop also uses `defer`: https://github.com/async-interop/event-loop/blob/master/src/Loop.php#L148

**Comment by clue** [comment]
Technically, this PR is a BC break and if we are to accept this, this will be part of the upcoming v0.5 release.

However, I would vote for keeping the method names as-is for now at least. If we are to accept this PR, then we'll remove `nextTick()` and only `futureTick()` remains.

Empirical evidence seems to suggest that:
* Most consumers of this lib don't use either
* Those that actually use `futureTick()` could probably switch from `nextTick()` without affecting operation

This means that while this PR *is* a BC break, most consumers of this library are likely compatible with the current v0.4 as well as the upcoming v0.5 release.

I'm not saying `futureTick()`, `defer()` or anything else makes any more sense, but I'd vote to move this discussion to another release.

**Comment by jsor** [comment]
@clue Good point, agreed. 👍

**Pull request merged**
