### PR TITLE
Remove Instances of Duplicate Word in Comments

### PR DESCRIPTION
**Pull request by broberts-dev**
Remove a duplicate word ("the") from the comment for `LoopInterface::addPeriodicTimer`.

### CODE REVIEW

**Review by clue — COMMENTED** [review]
@broberts-mrmc Thanks for looking into this and filing this PR! The same typo is also on the README.md, can you amend your changes? :+1:

**Comment by broberts-mrmc** [comment]
@clue It's done. I suppose I should have searched the source for other occurrences and I would have found that one too. In any case, the README.md has been fixed in this pull request also. I figure every little thing helps, though this one is mostly superficial.

**Review by jsor — APPROVED** [review]

**Review by clue — COMMENTED** [review]
@broberts-mrmc Thanks for the update! May I ask you to squash your changes into one commit?

```bash
$ GIT_SEQUENCE_EDITOR="sed -i -re 's/^pick (c9f227d)/fixup \1/'" git rebase -i HEAD~2
```

**Comment by broberts-mrmc** [comment]
@clue Curious: Since the commits are part of one branch/fork, what real value is there in squashing the commits given it’s as much trouble to do so as to make the changes.

**Pull request closed without merging**
