### PR TITLE
StreamSelectLoop: Fix erroneous zero-time sleep

### PR DESCRIPTION
**Pull request by joshdifabio**
See #48.

### CODE REVIEW

**Comment by clue** [comment]
Nice find :+1:

**Comment by clue** [comment]
Ping @joshdifabio, what do you think about adding a test here?

Also, may I ask you to rebase this on the new "0.4" branch so we get this in for the upcoming v0.4.3 release? :shipit:

**Comment by joshdifabio** [comment]
I can't see an easy way to test this, but I'm also very busy and this isn't near the top of my priority list. Please feel free to close this PR and make the change yourself if that's easier.

**Comment by jsor** [comment]
Superseded by #93

**Pull request closed without merging**
