### PR TITLE
[RFC] Global Loop (simplified)

### PR DESCRIPTION
**Pull request by jsor**
This is a simplified alternative to #77 introducing a global loop on top of the current API and being backward compatible.

To use the global loop, `Factory::create()` can be simply replaced by `GlobalLoop::get()`.

The global loop is run automatically in a shutdown function, so no need to call `run()` manually. This behaviour can be disabled by calling `GlobalLoop::disableRunOnShutdown()` or by simply calling `GlobalLoop::get()->run()` .

This incorporates the suggestion from @mbonneau (https://github.com/reactphp/event-loop/pull/77#issuecomment-279186122) and also addresses https://github.com/reactphp/event-loop/pull/77#issuecomment-282234913.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
I'm in favour of this, I think it's a great step in the right direction :+1:

**Comment by mbonneau** [comment]
Would the plan be to have the react libraries to start using `GlobalLoop::get()` if a loop was not provided by the user?

**Comment by jsor** [comment]
@mbonneau i'm not sure i'd like an optional loop parameter. I'd prefer simple facade api's on top of the current api's, eg. something i proposed in #77 or @clue in reactphp/socket-client#38 which then use the global loop.

**Comment by justinwilaby** [comment]
It's been almost 2 years since this PR was created and it seems to be approved. Are there still plans to adopt this?

**Comment by WyriHaximus** [comment]
Closing this as it has been resolved through #226 and follow up PR's

**Pull request closed without merging**
