### PR TITLE
[WIP] LibUvLoop: Add new LibUvLoop (unofficial ext-libuv)

### PR DESCRIPTION
**Pull request by steverhoades**
This event loop is currently passing on a debian system with PHP 5.6 and php-uv available here https://github.com/steverhoades/php-uv/tree/libuv-1.0

There are still some segfault issues with the php-uv extension that I am trying to fix.

### CODE REVIEW

**Comment by steverhoades** [comment]
All tests are now passing, what else is needed to get this merged?

/cc @WyriHaximus @cboden

**Comment by WyriHaximus** [comment]
@steverhoades this is awesome news :D!  Got two small things: So I'm missing an `ext-uv` in composer.json, not sure if it should point to your repo or another? Another thing is a mention about the UV event loop in the readme file :+1:

**Comment by steverhoades** [comment]
@WyriHaximus I'll get that updated it should now point to bwoebi's php-uv fork as his fork is being actively maintained.  The other consideration that I just thought of is that this version of php-uv only supports PHP 7.  We could do a version check for the time being.  I'll take a look at the extension and see what effort would be required to port a version for PHP 5 -

**Comment by WyriHaximus** [comment]
@steverhoades Having at for PHP7 already makes me really happy. PHP5 is a must tbh and a version check would do for now, please ping me if I can help you test PHP5 support

**Comment by sinasalek** [comment]
Has this been merged ?

**Comment by cebe** [comment]
@sinasalek no.

**Comment by clue** [comment]
Unfortunately this is still marked as WIP, is there anything we can do to help this progress? :+1:

**Comment by clue** [comment]
Ping @steverhoades, what's the status here? :shipit:

**Comment by clue** [comment]
Thank you for working on this and helping push this forward! This is kind of an old PR and it looks like #112 is the most up to date version of this feature, so I'm closing this one in favor of the newer PR :shipit: This should help us focusing on shipping this in a future version :+1:

**Pull request closed without merging**
