### PR TITLE
change properties's access privilege to protected.

### PR DESCRIPTION
**Pull request by huyanping**
in order to get read stream, write stream and timer count through inheritance. like:$loop->getReadStreamCount();

### CODE REVIEW

**Comment by cboden** [comment]
What do you need access to these for?

**Comment by cebe** [comment]
> in order to get read stream, write stream and timer count through inheritance. like:$loop->getReadStreamCount();

If you have the need to such a method it would be better to send a PR adding it instead of making all properties protected...

**Comment by clue** [comment]
> in order to get read stream, write stream and timer count through inheritance. like:$loop->getReadStreamCount();

You can also build a decorating class that merely keeps track of these via composition.

Perhaps https://github.com/WyriHaximus/reactphp-event-loop-inspector is also a good start?

**Comment by huyanping** [comment]
@clue,
Thx, that is a good way to solve the problem.

**Pull request closed without merging**
