### PR TITLE
[WIP] moved signal handling tests to AbstractLoopTest

### PR DESCRIPTION
**Pull request by cebe**
do not merge yet, this currently fails on various combinations of php versions on my machine, created the PR to see how it works on travis.

I'd like to fix it after #45 is merged to have tests
run against all systems.

### CODE REVIEW

**Comment by clue** [comment]
Ping @cebe, what's the status here? :shipit:

**Comment by cebe** [comment]
good question! I do not even remember that I did this :)
I might take a look at what this does the next days though.

**Comment by cebe** [comment]
Sorry, not going to happen within the next 1-2month. but I might eventually come back to this.

**Comment by clue** [comment]
I'll assume this is resolved via #104 and will close this for now, please feel free to report back otherwise :+1:

**Comment by cebe** [comment]
seems to be fine. If its not, the changes are conflicting anyway.

**Pull request closed without merging**
