### PR TITLE
Test against PHP7

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by cboden** [comment]
Anything you can do to get the test suite to run?  :)

**Comment by WyriHaximus** [comment]
Going to be an interesting one since it's the extension compile that seems to fail :/. Will look into it :smile:

**Comment by antares993** [comment]
Hello
As far as I tested none of the extensions compiles under PHP7, but the tests for StreamSelectLoop don't fail. I think adding `if [[ ... && ... && "$TRAVIS_PHP_VERSION" != "7" ]]` in `travis-init.sh` should get the test suite to run.

**Comment by cboden** [comment]
Covered in #45

**Comment by WyriHaximus** [comment]
:+1:

**Pull request closed without merging**
