### PR TITLE
ExtEvLoop: Add new ExtEvLoop (PECL source ext-ev)

### PR DESCRIPTION
**Pull request by steverhoades**
Brought https://github.com/reactphp/react/pull/178 inline with current branch.  Fixed unit tests.  added additional unit test for periodic timer.

### CODE REVIEW

**Comment by shouze** [comment]
ping @cboden @steverhoades @markkimsal how can we move forward on https://github.com/reactphp/event-loop/pull/12 & https://github.com/reactphp/event-loop/pull/25 to make something mergeable at some time? This is already a long story for the 2 PRs, should be sad to give up now ;)

**Comment by cboden** [comment]
Tested on PHP7 with updated Ev extension over the weekend. Still seeing memory leaks.

**Comment by WyriHaximus** [comment]
@cboden Just ran it with the `test-memory.php` from https://github.com/reactphp/event-loop/pull/59 can't see any leak, attached the [output](https://github.com/reactphp/event-loop/files/588096/test.txt).

**Comment by clue** [comment]
I'd like to make this actionable :shipit: 

What is the current status here? How is this related to #25?

Is there still interest in this ticket or can either be closed?

**Comment by nrk** [comment]
@clue both this PR and #25 target the [same PECL extension](https://pecl.php.net/package/ev) and they look very similar aside from a few minor differences. On a related note our own `React\EventLoop\LibEvLoop` is based on a [unmaintained extension](https://github.com/m4rw3r/php-libev) which is not available on PECL and is not even compatible with PHP 7, so we should just take the chance and switch to the official pecl extension which is actively developed and definitely more stable then it was back in 2014 when this PR was opened.

**Comment by clue** [comment]
Thank you for working on this and helping push this forward! This is kind of an old PR and it looks like #97 is the most up to date version of this feature, so I'm closing this one in favor of the newer PR :shipit: This should help us focusing on shipping this in a future version :+1:

**Pull request closed without merging**
