### PR TITLE
Replace 3rd party domains in examples with example.com 

### PR DESCRIPTION
**Pull request by WyriHaximus**
While using a big tech 3rd party domain like google.com is guaranteed to work, there are special domains like example.com set up for this since the dawn of the internet.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
When this PR is approved and merged I'll file PR's for the other repositories that use 3rd party domains for things like this. But until then, the aim is to keep the discussion about this in one location.

**Comment by Bilge** [comment]
Why not use the canonical documentation domains provided by IANA? e.g. www.example.com, www.example.org. That's what they're there for.

**Comment by SimonFrings** [comment]
@Bilge Good point, but I don't really see a big difference in using `www.example.com`, `www.example.org` or `reactphp.org`. That's why I leave that decision up to @WyriHaximus and will approve whatever he decides :D

**Comment by WyriHaximus** [comment]
@SimonFrings To be honest I think @Bilge's point is pretty good that those domains are specifically for this purpose. So I'm leaning more to use `example.com` then to use `reactphp.org` at this point. Unless @clue has good reasons to go with either of those two.

**Comment by SimonFrings** [comment]
@WyriHaximus Fine by me 👍

**Comment by WyriHaximus** [comment]
Updated the PR changing everything to `example.com`

**Review by SimonFrings — COMMENTED** [review]
One last question, should it be `www.example.com` or just `example.com`. Just asking because PR title doesn't match your changes (pls don't hate me 😅)

**Comment by WyriHaximus** [comment]
@SimonFrings It was mainly about updating the domain name, but updated the PR title and commit message :+1: . If you prefer to have it fully in line, I can also update the branch name and file a new PR from that 😜.

**Comment by Bilge** [comment]
Can you guys quit bikeshedding in my feed already.

**Review by SimonFrings — APPROVED** [review]
Goodbye google :+1:

**Review by clue — APPROVED** [review]
@WyriHaximus Thank you for looking into this and updating to `example.com`! :shipit:

**Pull request merged**
