### PR TITLE
Run tests on Windows using AppVeyor (backported to v0.4)

### PR DESCRIPTION
**Pull request by clue**
Backported #76 (originally by @WyriHaximus) to the v0.4 release branch so that tests also work here.

### CODE REVIEW

**Comment by clue** [comment]
@WyriHaximus Do the build errors on AppVeyor make any sense to you? Should this be fixed here or should we just accept this despite the build errors?

**Comment by WyriHaximus** [comment]
@clue no clue, it's windows so it fails at times sadly enough. But you could try restarting the build. The JSON parse errors or very vague. You could remove the cache directive or change it to `.json` as we  don't have a `.lock`. My bad, should have done that while filing the initial PR for AppVeyor

**Comment by clue** [comment]
I've now triggered a rebuild several times already, but the build keeps failing at different places all the time... :confused:

**Comment by WyriHaximus** [comment]
Gah 😕

**Comment by clue** [comment]
If you look at the build history, you'll see that *EVERY* build failed, except the one where you've added AppVeyor :-) It even failed merging these changes to the master branch.

https://ci.appveyor.com/project/clue/event-loop/history

What should we do here? Not a big fan of marking working code as broken, so we should either look into fixing this ASAP or remove AppVeyor again?

**Comment by WyriHaximus** [comment]
Looks like `7.x` is the most consistent failure. We could try removing it from the matrix and otherwise ditch AppVeyor all together.

**Comment by jsor** [comment]
I've have absolutely no idea what's going on there and as long as we don't have someone who can reliably maintain the AppVeyor configuration, i'd vote for removing it alltogether.

**Comment by WyriHaximus** [comment]
My main reason for doing this was #71 and if we can't do that reliable we should indeed remove it. For personal projects I have less of an issue with failing some jobs on windows. But for react we can't afford that because it's time consuming to baby sit all the builds.

**Comment by clue** [comment]
I have to agree here :+1: 

I'd rather test on Windows manually and fix any issues as they occur.

FWIW, AppVeyor did *NOT* help reproducing the error from #71, it actually passed, so...

@WyriHaximus Can you file a PR that supersedes this and #76?

**Comment by WyriHaximus** [comment]
@clue so I've just file a reverse PR: #79
@clue can you also ditch the webhook and delete the project on AppVeyor so it doesn't sneak up on us again?

**Pull request closed without merging**
