### PR TITLE
StreamSelectLoop: Use fresh time so Timers added during stream events are accurate

### LINKED ISSUE #42: StreamSelectLoop:Timers added during stream events are not accurate
New timers are scheduled relative to a local time kept in the timers class, which is only updated when Timers::tick() is run. However, when there are no scheduled tick callbacks, StreamSelectLoop will wait until the next scheduled timer (or infinite, if there are none) for stream activity, which prevents Timers::tick() from being called regularly and updating its local time. If a new timer is added in response to a stream event, it will be shortened by whatever period of time was spent waiting for stream activity (or, if the new timer's length is shorter than was spent waiting, the timer will be resolved immediately).

I believe a potential solution is:

```
diff --git a/src/Timer/Timers.php b/src/Timer/Timers.php
index c183a63..bebe552 100644
--- a/src/Timer/Timers.php
+++ b/src/Timer/Timers.php
@@ -30,7 +30,7 @@ class Timers
     public function add(TimerInterface $timer)
     {
         $interval = $timer->getInterval();
-        $scheduledAt = $interval + $this->getTime();
+        $scheduledAt = $interval + microtime(true);

         $this->timers->attach($timer, $scheduledAt);
         $this->scheduler->insert($timer, -$scheduledAt);
```

I can provide example reproducing scripts if preferred.

### PR DESCRIPTION
**Pull request by andrewminerd**

### CODE REVIEW

**Comment by clue** [comment]
I understand this is a bit tricky, but can we add a test case for this? :+1:

**Comment by andrewminerd** [comment]
Haha, had a feeling that was coming. :-p Yeah, a little tricky, but I'll see what I can do!

**Comment by WyriHaximus** [comment]
IIRC partial mocks could do the trick :)

**Comment by cebe** [comment]
for mocking time functions you can override them inside of a namespace, like it's done here: https://github.com/yiisoft/yii2/blob/ae1fbdd737720c614ca3ee7e2d94e0173e40c46d/tests/framework/caching/CacheTestCase.php#L3-L24

**Comment by andrewminerd** [comment]
I apologize for the lapse...

@cebe Thanks for the suggestion! However, this would require enabling process isolation during the PHPUnit run to prevent the time functions from being replaced in all tests (some of which seem to require 'real' time functions), so for now I haven't gone this route. Perhaps @clue could indicate whether this is something that would be acceptable.

@WyriHaximus Thanks as well! Unfortunately, as the current fix uses microtime directly, I could really only mock out half of the microtime calls, which, while master failed and my branch passed, felt a bit like cheating. Another option would be to create a method that just wraps microtime which could be used in both locations within the Timers class and be mocked out in the test.

For now, I've used a real sleep in the test. Obviously this isn't optimal, but felt like the least fragile method at present. If you'd prefer a different solution, let me know!

**Comment by cebe** [comment]
> @cebe Thanks for the suggestion! However, this would require enabling process isolation during the PHPUnit run to prevent the time functions from being replaced in all tests (some of which seem to require 'real' time functions), so for now I haven't gone this route. Perhaps @clue could indicate whether this is something that would be acceptable.

This should not be a problem, as the mock function I linked is implemented in such a way that it returns the mock value if a property of the test is not null but the real time if the test property is null. This way you can enable mock by simply setting the value.

**Comment by clue** [comment]
The tests may not be perfect, but they LGTM until we can come up with anything better :+1: Can you amend your changes to conform to the existing code style (PSR-2)?

**Comment by Tatikoma** [comment]
Thanks for fix. I got this issue with predis-async library and this fix worked for me.

**Pull request merged**
