### PR TITLE
Fix for PHP 7 fatal error on duplicate parameter names in closures

### PR DESCRIPTION
**Pull request by ondrejmirtes**
PHP 7 does not like duplicate parameter names: https://3v4l.org/usQhl

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
The build failed on PHP 5.5 because the composer.json requires PHPUnit version that requires PHP 5.6.

**Comment by WyriHaximus** [comment]
That is interesting because the 5.4 build didn't fail. We don't specify phpunit in composer.json, the phpunit versions are supplied by travis

**Comment by clue** [comment]
The changes LGTM and make perfect sense :+1: 

Though I'm a bit surprised, has #27 been solved yet? Afaict nobody has managed to build the required extensions, so this code will not actually run? (Only the `StreamSelectLoop` should work)

**Comment by dakota** [comment]
Event 2.0 has been released with full PHP7 support. What is needed to get this to be merged?

**Comment by ondrejmirtes** [comment]
We are already using PECL event 2.0 extension with PHP 7.0.3 with this patch and everything works fine.

**Comment by dakota** [comment]
@ondrejmirtes I'm busy patching our local install. Wondering when this will end up in a event-loop release.

**Comment by ondrejmirtes** [comment]
I will contact ReactPHP maintainers in order to ask them what can we do to bring ReactPHP up to speed.

**Comment by cebe** [comment]
https://github.com/reactphp/event-loop/pull/45 includes this fix and adds also tests for php 7.

**Comment by clue** [comment]
> Wondering when this will end up in a event-loop release.

At the moment the above changes are not tested in our CI setup. I assume this will be accepted once we come up with some installation instructions for the required extensions, so perhaps anybody may help with #27 or #45?

**Comment by cebe** [comment]
@clue #45 is ready to merge. libev and libevent do not support php7 so there is nothing to fix from our side  atm.

**Comment by cboden** [comment]
Merged in via #45

**Pull request closed without merging**
